<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
<TITLE>CurveElement Object</TITLE>
<style>@import url(/Office.css);</style>
<link disabled rel="stylesheet" href="/MSOffice.css"></HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1 class=RH1><A NAME="usobjcurveelement"></A>CurveElement Object</H1>

<P>
<P class=ALNSR>
<OBJECT ID="hhobj_477" TYPE="application/x-oleobject" CLASSID="clsid:adb880a6-d8ff-11cf-9377-00aa003b7a11">
        <param name="Command" value="ALink">
        <param name="Font" value="Verdana,8,1">
        <param name="Text" value="Text:See Also">
        <param name="Flags" value=",,1">
        <param name="Item1" value="">
        <param name="Item2" value="usobjCurveElementC">
</OBJECT>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<OBJECT ID="hhobj_478" TYPE="application/x-oleobject" CLASSID="clsid:adb880a6-d8ff-11cf-9377-00aa003b7a11">
        <param name="Command" value="ALink">
        <param name="Font" value="Verdana,8,1">
        <param name="Text" value="Text:Example">
        <param name="Flags" value=",,1">
        <param name="Item1" value="">
        <param name="Item2" value="usobjCurveElementX">
</OBJECT>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<OBJECT ID="hhobj_479" TYPE="application/x-oleobject" CLASSID="clsid:adb880a6-d8ff-11cf-9377-00aa003b7a11">
        <param name="Command" value="ALink">
        <param name="Font" value="Verdana,8,1">
        <param name="Text" value="Text:Properties">
        <param name="Flags" value=",,1">
        <param name="Item1" value="">
        <param name="Item2" value="usobjCurveElementP">
</OBJECT>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<OBJECT ID="hhobj_480" TYPE="application/x-oleobject" CLASSID="clsid:adb880a6-d8ff-11cf-9377-00aa003b7a11">
        <param name="Command" value="ALink">
        <param name="Font" value="Verdana,8,1">
        <param name="Text" value="Text:Methods">
        <param name="Flags" value=",,1">
        <param name="Item1" value="">
        <param name="Item2" value="usobjCurveElementM">
</OBJECT>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<OBJECT ID="hhobj_481" TYPE="application/x-oleobject" CLASSID="clsid:adb880a6-d8ff-11cf-9377-00aa003b7a11">
        <param name="Command" value="ALink">
        <param name="Font" value="Verdana,8,1">
        <param name="Text" value="Text:Events">
        <param name="Flags" value=",,1">
        <param name="Item1" value="">
        <param name="Item2" value="usobjCurveElementE">
</OBJECT>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<OBJECT ID="hhobj_482" TYPE="application/x-oleobject" CLASSID="clsid:adb880a6-d8ff-11cf-9377-00aa003b7a11">
        <param name="Command" value="ALink">
        <param name="Font" value="Verdana,8,1">
        <param name="Text" value="Text:Specifics">
        <param name="Flags" value=",,1">
        <param name="Item1" value="">
        <param name="Item2" value="usobjCurveElementS">
</OBJECT>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<OBJECT ID="hhobj_483" TYPE="application/x-oleobject" CLASSID="clsid:adb880a6-d8ff-11cf-9377-00aa003b7a11">
        <param name="Command" value="ALink">
        <param name="Font" value="Verdana,8,1">
        <param name="Text" value="Text:Interfaces">
        <param name="Flags" value=",,1">
        <param name="Item1" value="">
        <param name="Item2" value="usobjCurveElementI">
</OBJECT>
</P>

<P class=T>
A kind of <A href="usobjElement.htm">Element</A> that corresponds to a MicroStation curve element.
</P>
<P class=RL><B>Remarks</B></P>
<P>
If you have a generic <B>Element</B> object (as the result of a <A href="usmthScan.htm">Scan</A>, for example),
    you can determine whether it's a <B>CurveElement</B> by examining the element's <A href="usproIsCurveElement.htm">IsCurveElement</A>
    property. If this property returns <B>True</B>, you can extract the element's implementation
    of <B>CurveElement</B> by calling the element's <A href="usproAsCurveElement.htm">AsCurveElement</A> property. (You can accomplish
    the same thing by assigning the element to a variable of the type <B>CurveElement</B>. But
    <B>Element</B>.<B>AsCurveElement</B> saves you a step.)
    <P>You cannot use the <B>New</B> keyword to create a <B>CurveElement</B> object.
    Rather, use the global function <A href="usmthCreateCurveElement1.htm">CreateCurveElement1</A>.</P>
    <P>Remember that a newly-created element (of any type) is an "invisible orphan:"
    It does not appear on the screen, nor is it part of any design file.</P>
    <UL>
        <LI>To display an element on the screen (regardless of whether it's part of a design file),
            call the element's <A href="usmthRedraw.htm">Redraw</A> method.</LI>
        <LI>To add the element to the current design file (regardless of whether it's displayed on the screen),
            call <A href="usmthAddElement.htm">AddElement</A> on the appropriate <A href="usobjModelReference.htm">ModelReference</A> object (typically, <A href="usproActiveModelReference.htm">ActiveModelReference</A>).</LI>
    </UL>
    <P></P>
    <P><B>Example</B></P>
    <PRE><CODE>    Dim oCurve As <B>CurveElement</B>
    Set oCurve = <B>CreateCurveElement1</B>(...) ' Click on the link above to
                                             ' see the arguments list for
                                             ' <B>CreateCurveElement1</B>.
    With oCurve
        ' ...Set other properties of oCurve, if you wish.
    End With
    <B>ActiveModelReference</B>.<B>AddElement</B> oCurve
    oCurve.<B>Redraw</B></CODE></PRE>
</P>
<P class=RL><B>Version</B></P>
<P>
08.00.00
</P>
</BODY>
</HTML>
