<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
<TITLE>Line Element Creation Command</TITLE>
<style>@import url(/Office.css);</style>
<link disabled rel="stylesheet" href="/MSOffice.css"></HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1 class=RH1>Line Element Creation Command</H1>

<P class=T>
This example illustrates the implementation of an element creation command.  The following
            code starts the command by creating an instance of the class that implements <A href="usobjIPrimitiveCommandEvents.htm">IPrimitiveCommandEvents</A>
            and invoking <A href="usmthStartPrimitive.htm">StartPrimitive</A> passing in that instance as an argument.
</P>
<PRE class=CT><CODE>
Sub PlaceLine()
    <A href="usproCommandState.htm">CommandState</A>.StartPrimitive New clsPlaceLineCommand
End Sub

</CODE></PRE>
<P class=T>
This following code must be in a class that implements IPrimitiveCommandEvents. In this example,
            it is in the class clsPlaceLineCommand.
</P>
<PRE class=CT><CODE>
Implements IPrimitiveCommandEvents

Private m_atPoints(0 To 1) As <A href="usudtPoint3d.htm">Point3d</A>
Private m_nPoints As Integer

Private Sub IPrimitiveCommandEvents_<A href="usevtCleanup.htm">Cleanup</A>()

End Sub

Private Sub IPrimitiveCommandEvents_<A href="usevtDataPoint.htm">DataPoint</A>(<A href="usproPoint.htm">Point</A> As Point3d, ByVal <A href="usproView.htm">View</A> As <A href="usobjView.htm">View</A>)

    If m_nPoints = 0 Then
        CommandState.<A href="usmthStartDynamics.htm">StartDynamics</A>
        m_atPoints(0) = Point
        m_nPoints = 1
        <A href="usmthShowPrompt.htm">ShowPrompt</A> "Place end point"
    ElseIf m_nPoints = 1 Then
        m_atPoints(1) = Point
        Dim oEl As <A href="usobjLineElement.htm">LineElement</A>
        Set oEl = <A href="usmthCreateLineElement1.htm">CreateLineElement1</A>(Nothing, m_atPoints)
        <A href="usproActiveModelReference.htm">ActiveModelReference</A>.<A href="usmthAddElement.htm">AddElement</A> oEl
        oEl.<A href="usmthRedraw.htm">Redraw</A>
        m_atPoints(0) = m_atPoints(1)
    End If

End Sub


Private Sub IPrimitiveCommandEvents_<A href="usevtDynamics.htm">Dynamics</A>(Point As Point3d, ByVal View As View, ByVal DrawMode As <A href="usenmMsdDrawingMode.htm">MsdDrawingMode</A>)
    If m_nPoints = 1 Then
        m_atPoints(1) = Point
        Dim oEl As LineElement
        Set oEl = CreateLineElement1(Nothing, m_atPoints)
        oEl.Redraw DrawMode
    End If
End Sub

Private Sub IPrimitiveCommandEvents_<A href="usproKeyin.htm">Keyin</A>(ByVal Keyin As String)

End Sub

Private Sub IPrimitiveCommandEvents_<A href="usmthReset.htm">Reset</A>()
    CommandState.StartPrimitive Me
    m_nPoints = 0
End Sub

Private Sub IPrimitiveCommandEvents_<A href="usevtStart.htm">Start</A>()
    <A href="usmthShowCommand.htm">ShowCommand</A> "VBA PlaceLine Example"
    ShowPrompt "Select start of line"
End Sub

</CODE></PRE>
