<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
<TITLE>Illustrates Differences in ProjectPointOnPerpendicular Methods</TITLE>
<style>@import url(/Office.css);</style>
<link disabled rel="stylesheet" href="/MSOffice.css"></HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1 class=RH1>Illustrates Differences in ProjectPointOnPerpendicular Methods</H1>

<P class=T>
Demonstrates the differences in the ProjectPointOnPerpendicular methods.
            These examples draw lines to show the returned points.
</P>
<PRE class=CT><CODE>
Sub RunLineSample()
    Dim ele As <A href="usobjLineElement.htm">LineElement</A>
    Dim temp As LineElement
    Dim pntProjected As <A href="usudtPoint3d.htm">Point3d</A>
    Dim pntStart As Point3d

    Set ele = <A href="usmthCreateLineElement2.htm">CreateLineElement2</A>(Nothing, <A href="usmthPoint3dFromXY.htm">Point3dFromXY</A>(0, 5), Point3dFromXY(5, 5))
    ele.<A href="usproColor.htm">Color</A> = 3
    <A href="usproActiveModelReference.htm">ActiveModelReference</A>.<A href="usmthAddElement.htm">AddElement</A> ele
    ele.<A href="usmthRedraw.htm">Redraw</A>

    pntStart = Point3dFromXY(7, 0)

    pntProjected = ele.<A href="usmthProjectPointOnPerpendicular.htm">ProjectPointOnPerpendicular</A>(pntStart, <A href="usmthMatrix3dIdentity.htm">Matrix3dIdentity</A>)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 0
    ActiveModelReference.AddElement temp
    temp.Redraw

    pntProjected = ele.<A href="usmthProjectPointOnPerpendicular2.htm">ProjectPointOnPerpendicular2</A>(pntStart, Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 1
    ActiveModelReference.AddElement temp
    temp.Redraw
End Sub
Sub RunShapeSample()
    Dim pnts(0 To 2) As Point3d
    Dim ele As <A href="usobjShapeElement.htm">ShapeElement</A>
    Dim temp As LineElement
    Dim pntProjected As Point3d
    Dim pntStart As Point3d

    pnts(0) = Point3dFromXY(0, 0)
    pnts(1) = Point3dFromXY(7, 0)
    pnts(2) = Point3dFromXY(3.5, 10)
    Set ele = <A href="usmthCreateShapeElement1.htm">CreateShapeElement1</A>(Nothing, pnts)
    ele.Color = 3
    ActiveModelReference.AddElement ele
    ele.Redraw

    pntStart = Point3dFromXY(3.5, 5)

    pntProjected = ele.ProjectPointOnPerpendicular(pntStart, Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 0
    ActiveModelReference.AddElement temp
    temp.Redraw

    pntProjected = ele.<A href="usmthProjectPointOnPerpendicular1.htm">ProjectPointOnPerpendicular1</A>(pntStart, Point3dFromXY(0, 1), Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 1
    ActiveModelReference.AddElement temp
    temp.Redraw

    pntProjected = ele.ProjectPointOnPerpendicular1(pntStart, Point3dFromXY(12, 3), Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 2
    ActiveModelReference.AddElement temp
    temp.Redraw

    pntProjected = ele.ProjectPointOnPerpendicular1(pntStart, Point3dFromXY(2, -1), Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 4
    ActiveModelReference.AddElement temp
    temp.Redraw

    pntStart = Point3dFromXY(-2, -2)

    pntProjected = ele.ProjectPointOnPerpendicular(pntStart, Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 0
    ActiveModelReference.AddElement temp
    temp.Redraw

    pntProjected = ele.ProjectPointOnPerpendicular1(pntStart, Point3dFromXY(12, 3), Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 1
    ActiveModelReference.AddElement temp
    temp.Redraw

    pntProjected = ele.ProjectPointOnPerpendicular2(pntStart, Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 2
    ActiveModelReference.AddElement temp
    temp.Redraw
End Sub
Sub RunEllipseSamples()
    Dim ele As <A href="usobjEllipseElement.htm">EllipseElement</A>
    Dim temp As LineElement
    Dim pntProjected As Point3d
    Dim pntStart As Point3d

    Set ele = <A href="usmthCreateEllipseElement2.htm">CreateEllipseElement2</A>(Nothing, Point3dFromXY(4, 4), 3, 3, Matrix3dIdentity)
    ele.Color = 3
    ActiveModelReference.AddElement ele
    ele.Redraw

    pntStart = Point3dFromXY(14, 4)

    pntProjected = ele.ProjectPointOnPerpendicular(pntStart, Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 0
    ActiveModelReference.AddElement temp
    temp.Redraw

    pntProjected = ele.ProjectPointOnPerpendicular1(pntStart, <A href="usmthPoint3dAdd.htm">Point3dAdd</A>(ele.<A href="usproCenterPoint.htm">CenterPoint</A>, Point3dFromXY(1, 0)), Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 1
    ActiveModelReference.AddElement temp
    temp.Redraw

    pntProjected = ele.ProjectPointOnPerpendicular1(pntStart, Point3dAdd(ele.CenterPoint, Point3dFromXY(-1, 0)), Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 2
    ActiveModelReference.AddElement temp
    temp.Redraw

    pntProjected = ele.ProjectPointOnPerpendicular2(pntStart, Matrix3dIdentity)
    Set temp = CreateLineElement2(Nothing, pntStart, pntProjected)
    temp.Color = 4
    ActiveModelReference.AddElement temp
    temp.Redraw
End Sub

</CODE></PRE>
