<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
<TITLE>Elements and Levels</TITLE>
<style>@import url(/Office.css);</style>
<link disabled rel="stylesheet" href="/MSOffice.css"></HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1 class=RH1>Elements and Levels</H1>

<P class=T>
This example illustrates techniques for controlling an element's level.
</P>
<PRE class=CT><CODE>
Sub CreateAtLevel()
    Dim oNewElement As <A href="usobjElement.htm">Element</A>
    Dim points(1) As <A href="usudtPoint3d.htm">Point3d</A>
    Dim oSaveLevel As <A href="usobjLevel.htm">Level</A>

    ' Initialize the points of the line
    With points(0)
        .x = 0.682
        .Y = -0.43
    End With
    With points(1)
        .x = -0.12
        .Y = -0.53
    End With

    '  The line gets active level when it is created. Then this code
    '  immediately changes the level.  Then it adds the element
    '  to the current model. Finally it displays the level.
    '
    Set oNewElement = <A href="usmthCreateLineElement1.htm">CreateLineElement1</A>(Nothing, points)
    Set oNewElement.<A href="usproLevel.htm">Level</A> = <A href="usproActiveDesignFile.htm">ActiveDesignFile</A>.<A href="usproLevels.htm">Levels</A>.FindByCode(10)
    <A href="usproActiveModelReference.htm">ActiveModelReference</A>.<A href="usmthAddElement.htm">AddElement</A> oNewElement
    oNewElement.<A href="usmthRedraw.htm">Redraw</A>

    '  The next element will be one master unit above
    '  the previous unit.
    '
    points(0).Y = points(0).Y + 1

    '  This time, set the element's level by changing the active level
    '  prior to creating the element.
    '
    Set oSaveLevel = <A href="usproActiveSettings.htm">ActiveSettings</A>.Level
    ActiveSettings.Level = ActiveDesignFile.Levels.FindByCode(15)

    Set oNewElement = <A href="usmthCreateTextElement1.htm">CreateTextElement1</A>(Nothing, "ON LEVEL 15", points(0), <A href="usmthMatrix3dIdentity.htm">Matrix3dIdentity</A>)
    ActiveModelReference.AddElement oNewElement
    oNewElement.Redraw

    ActiveSettings.Level = oSaveLevel

End Sub

</CODE></PRE>
