<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
<HEAD>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=Windows-1252">
<TITLE>Changing Reference Origin and Rotation</TITLE>
<style>@import url(/Office.css);</style>
<link disabled rel="stylesheet" href="/MSOffice.css"></HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1 class=RH1>Changing Reference Origin and Rotation</H1>

<P class=T>

</P>
<PRE class=CT><CODE>
' SetOriginTo sets the origin to a specific point by calculating
' the distance from the specified point to the destination, and
' then moving the attachment that distance
Sub SetOriginTo(att As <A href="usobjAttachment.htm">Attachment</A>, destination As <A href="usudtPoint3d.htm">Point3d</A>)
    Dim distance As Point3d

    distance = <A href="usmthPoint3dSubtract.htm">Point3dSubtract</A>(destination, att.<A href="usproMasterOrigin.htm">MasterOrigin</A>)
    att.<A href="usmthMove.htm">Move</A> distance, True
End Sub

'   SetRotationTo sets the rotation to a specific value by
'   calculating the difference between the desired rotation
'   and the current rotation, and using that value to rotate
'   the attachment.
Sub SetRotationTo(att As Attachment, newRotation As Double)
    Dim mtrx As <A href="usudtMatrix3d.htm">Matrix3d</A>
    Dim currentRotation As Double

    mtrx = att.<A href="usproRotation.htm">Rotation</A>

    If <A href="usmthMatrix3dIsXYRotation.htm">Matrix3dIsXYRotation</A>(mtrx, currentRotation) Then
        Dim deltaToNewRotation As Double
        deltaToNewRotation = newRotation - currentRotation
        att.<A href="usmthRotate.htm">Rotate</A> att.MasterOrigin, 0, 0, deltaToNewRotation, 1
    End If
End Sub

'  MoveAndRotate uses the SetOriginTo and SetRotationTo
'  to set origin and rotation of an attachment.
Sub MoveAndRotate()
    Dim att As Attachment

    '  Start the NULL command so that UNDO does not
    '  combine this operation with some other operation
    <A href="usproCadInputQueue.htm">CadInputQueue</A>.<A href="usmthSendCommand.htm">SendCommand</A> "NULL"

    Set att = <A href="usproActiveModelReference.htm">ActiveModelReference</A>.<A href="usproAttachments.htm">Attachments</A>(1)

    att.<A href="usmthRedraw.htm">Redraw</A> msdDrawingModeErase

    SetOriginTo att, <A href="usmthPoint3dFromXY.htm">Point3dFromXY</A>(0, 20)
    SetRotationTo att, 3 * <A href="usmthPi.htm">Pi</A> / 2

    att.<A href="usmthRewrite.htm">Rewrite</A>
    att.Redraw

    '  Set MicroStation back to a reasonable state
    <A href="usproCommandState.htm">CommandState</A>.<A href="usmthStartDefaultCommand.htm">StartDefaultCommand</A>
End Sub


</CODE></PRE>
